### ISSUE TITLE
Please add back buttons to report issue screen, forgot password screen etc so user does not get stuck 

### ISSUE THREAD

**Issue by fredfalcon** [Bugheist/Flutter#100]
![7E648ADC-5356-4E8A-9081-5DD37E047C09](https://user-images.githubusercontent.com/7475382/179356542-3793bac1-d3e9-44db-8706-646b56ab1953.png)

**Comment by just-ary27** [comment]
For the report issue screen, I think it's fine, as the user is supposed to slide through the main screens: 
- Home
- Report
- Issues
- Leaderboard

**Comment by fredfalcon** [comment]
Stuck on login / signup 
![6E3081EE-3999-428B-AEE5-69A9356307A4](https://user-images.githubusercontent.com/7475382/180653303-59b26623-b656-4aaa-bf48-232f4badd254.png)
