### ISSUE TITLE
Change icon to have white background 

### ISSUE THREAD

**Issue by fredfalcon** [Bugheist/Flutter#101]

**Comment by fredfalcon** [comment]
Icon is a bit small now.  Would like to see it full size so the top right arrow touches the rounded corner 
![8F84BD4D-0B51-4372-8D77-0C11FC9EC248](https://user-images.githubusercontent.com/7475382/180653423-33a3ee4f-8ca6-48ab-9d18-c917d61501da.jpeg)

**Comment by just-ary27** [comment]
> Icon is a bit small now. Would like to see it full size so the top right arrow touches the rounded corner ![8F84BD4D-0B51-4372-8D77-0C11FC9EC248](https://user-images.githubusercontent.com/7475382/180653423-33a3ee4f-8ca6-48ab-9d18-c917d61501da.jpeg)

The icon quality degrades if we do that, imo a medium sized icon will be optimum, considering UX.

**Comment by fredfalcon** [comment]
Would like to see what it looks like.
