### ISSUE TITLE
Replace the home icon with the feed (remove home and switch it with feed so there are 3 icons)

### ISSUE THREAD

**Issue by fredfalcon** [Bugheist/Flutter#105]

**Comment by fredfalcon** [comment]
![8A980FAB-48C7-405A-93F6-1156551D1035](https://user-images.githubusercontent.com/7475382/180658436-89ac2af2-5920-45a8-be1b-5554685cdd70.jpeg)

**Comment by just-ary27** [comment]
I have an idea on home page to combine the newsletter, and social pages to make a single feed page which will be the home

**Comment by fredfalcon** [comment]
That sounds good,  for now it will be good to see the issues on the first tab.

**Comment by just-ary27** [comment]
Cool will do
