### ISSUE TITLE
Covert Issue Card to a Stateless Widget

### ISSUE THREAD

**Issue by Sparsh1212** [Bugheist/Flutter#12]
The Issue intro Card is something that will be used throughout the app. It will be good if we could convert it to a `Stateless` widget and use it as a Widget anywhere in the code. This will ensure the reusability of the code and will also make the code readable and clean.

**Comment by Sparsh1212** [comment]
@fredfalcon What do you think about this. Let me know. I would love to add a fix for this.

**Comment by fredfalcon** [comment]
sounds good
