### ISSUE TITLE
Add "Remember me" option while logging in

### ISSUE THREAD

**Issue by letsintegreat** [Bugheist/Flutter#142]
It is very tedious to log in every time I restart the app. How about we add a remember me option, which will save the credentials in SharedPreferences or something?

**Comment by fredfalcon** [comment]
Sounds good!

**Comment by letsintegreat** [comment]
Great, requesting to be assigned

**Comment by just-ary27** [comment]
Shared Preferences is **NOT** the right package for this :)

**Comment by letsintegreat** [comment]
@just-ary27 Realized that during development, and used flutter_secure_storage instead. Thanks!
