### ISSUE TITLE
Distorted image in IssuesPage

### ISSUE THREAD

**Issue by letsintegreat** [Bugheist/Flutter#150]
When the issue screenshot does not match the card's ratio, it is being distorted, which is looking really bad:

![image](https://user-images.githubusercontent.com/37345795/208290401-f7695c4e-82e0-40dd-aa23-f74dd5233c06.png)

I think we should crop the image to card's ratio, instead of showing a distorted image.

**Comment by just-ary27** [comment]
Hmm, good suggestion

**Comment by just-ary27** [comment]
Tested rn, doesn't look well tho, I think fill: BoxFit.cover is the best

**Comment by letsintegreat** [comment]
> Tested rn, doesn't look well tho, I think fill: BoxFit.cover is the best, Otherwise the design looks ugly

Yes, you are right. `cover` is what I had in mind.
