### ISSUE TITLE
Integrate leaderboard 

### ISSUE THREAD

**Issue by fredfalcon** [Bugheist/Flutter#16]
- [ ] make leaderboard style like new design

**Comment by Sparsh1212** [comment]
I would like to work on this feature.

**Comment by Sparsh1212** [comment]
I couldn't find the API for the leaderboard in the Django backend. Can you please guide me here?

**Comment by fredfalcon** [comment]
I think it’s userscore check here https://github.com/Bugheist/Fuse/blob/master/MainView.js

**Comment by Sparsh1212** [comment]
Found it! Thanks.
Will fix it by tomorrow for sure.
