### ISSUE TITLE
Integrate add an issue 

### ISSUE THREAD

**Issue by fredfalcon** [Bugheist/Flutter#17]
- [x] code first placeholder flutter
- [x] finish designing front end 
- [x] get approved design
- [x] code flutter for new design
- [ ] integrate to backend API

**Comment by Sparsh1212** [comment]
I would love to work on this.

**Comment by fredfalcon** [comment]
@just-ary27 this one would be great to have next

**Comment by just-ary27** [comment]
> @just-ary27 this one would be great to have next

Sure, I have one question tho. how do we send the image data?

**Comment by fredfalcon** [comment]
I think it’s a base64 you can check the backend code

**Comment by just-ary27** [comment]
> I think it’s a base64 you can check the backend code

Okay will check it!

**Comment by just-ary27** [comment]
API needs to be fixed imo, for this

**Comment by fredfalcon** [comment]
@just-ary27 I have created a test that creates an issue.  You can see it here:  

https://github.com/OWASP/BLT/blob/main/website/test_api.py#L9-L21

**Comment by just-ary27** [comment]
@fredfalcon I tried this I'm getting 400 Bad request for the following: 
```json
{
  user: {"username":"justary27"}, 
  url: "https://www.bugheist.com", 
  verified: false, 
  score: 0, 
  status: "closed", 
  description: "Test issue"
}
```
I've added the file as you did as per the multi-part request.
