### ISSUE TITLE
prepare and move the Flutter app over to the OWASP/BLT-Flutter repo

### ISSUE THREAD

**Issue by fredfalcon** [Bugheist/Flutter#205]

**Comment by solo-daemon** [comment]
@fredfalcon  I think We can fork this repo there .

**Comment by letsintegreat** [comment]
> @fredfalcon I think We can fork this repo there .

I don't think forking is the right way to do it. Forked repositories loose all information of issues and PRs as far as I know.

Quoting from [Transferring a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#:~:text=When%20you%20transfer%20a%20repository%20to%20a%20new%20owner%2C%20they%20can%20immediately%20administer%20the%20repository%27s%20contents%2C%20issues%2C%20pull%20requests%2C%20releases%2C%20projects%20(classic)%2C%20and%20settings.%20You%20can%20also%20change%20the%20repository%20name%20while%20transferring%20a%20repository.)

> When you transfer a repository to a new owner, they can immediately administer the repository's contents, issues, pull requests, releases, projects (classic), and settings. You can also change the repository name while transferring a repository.

I believe this is it ^

**Comment by just-ary27** [comment]
@fredfalcon weren't we shifting the other repository as BLT-Flutter to OWASP?
