### ISSUE TITLE
Russian Language not showing up in app

### ISSUE THREAD

**Issue by fredfalcon** [Bugheist/Flutter#25]
![image](https://user-images.githubusercontent.com/7475382/114911143-b20d7080-9dec-11eb-85e3-c022fe85c379.png)

**Comment by Sparsh1212** [comment]
I can try fixing this. assign this to me.

**Comment by Sparsh1212** [comment]
assign to me.

**Comment by ankit2001** [comment]
assign to me

**Comment by fredfalcon** [comment]
assign this to me
