### ISSUE TITLE
Integrate new user signup with captcha in the app

### ISSUE THREAD

**Issue by fredfalcon** [Bugheist/Flutter#30]

**Comment by ankit2001** [comment]
@fredfalcon , can you please elaborate it. We have to integrate it with django auth or adding somethung else?

**Comment by fredfalcon** [comment]
Yes, to signup from the app - we can use this https://pypi.org/project/django-rest-captcha/

**Comment by ankit2001** [comment]
Ohh thanks @fredfalcon .
Going to do it soon.
assign to me.

**Comment by just-ary27** [comment]
Do we need captcha? It is primarily for websites and is mostly used in web apps (also most plugins are for flutter web)

**Comment by fredfalcon** [comment]
@just-ary27 it doesn’t seem to work.  I’m stuck on the screen with no message after pressing the button.

**Comment by fredfalcon** [comment]
![350AB8D1-A5C6-48C2-8F99-95D882ECEF18](https://user-images.githubusercontent.com/7475382/180653331-b8e824eb-5d88-4da0-8501-c7b086c68c1a.png)

**Comment by just-ary27** [comment]
@fredfalcon if you're signing up for a new account, an email will be sent to your inbox for verification. (Just as on the website)

**Comment by fredfalcon** [comment]
Can you add a message?  I did not get the email either. I used a real one in the previous test.

**Comment by fredfalcon** [comment]
Logs are showing: Bad Request: /auth/registration/

**Comment by just-ary27** [comment]
> Logs are showing: Bad Request: /auth/registration/

Please check now, it will explain the problem in your signup
