### ISSUE TITLE
Add Sign Up in the APP

### ISSUE THREAD

**Issue by ankit2001** [Bugheist/Flutter#59]
[Figma Link](https://www.figma.com/file/s0xuxeU6O2guoWEfA9OElZ/Bugheist-Full-Design?node-id=385%3A9)

<img width="304" alt="signup" src="https://user-images.githubusercontent.com/44541855/122679649-55be3700-d209-11eb-83ca-4afd3dac7e08.png">

**Comment by ankit2001** [comment]
via Hubstaff
User: Ankit Choudhary

Project: Flutter - https://app.hubstaff.com/projects/1567799
Date Range: 06/26/21 - 06/26/21
Work session total: 4:40:56
Billable: Yes

Grand total: 4:40:56

**Comment by fredfalcon** [comment]
Signup is not working for me.  Can you please verify it works with signing up a new user and show the screens?

**Comment by ankit2001** [comment]
@fredfalcon, it is working when we use the https://bugheist.com URL instead of staging url, may be we have different authentication configured on both server. Will fix this in backend.

**Comment by fredfalcon** [comment]
It’s working now, the url was wrong.
