### ISSUE TITLE
Integrate Login Screen

### ISSUE THREAD

**Issue by fredfalcon** [Bugheist/Flutter#7]

**Comment by ankit2001** [comment]
@fredfalcon, you want this through api using bugheist backend? Or want to add some options in login screen.

**Comment by fredfalcon** [comment]
@ankit2001 yes it can be done like this - https://ohuru.tech/blog/2020/4/19/flutter-signuplogin-application-with-django-backend-3/

**Comment by ankit2001** [comment]
Please assign me this @fredfalcon , i am interested in contributing.

**Comment by fredfalcon** [comment]
Login works but we now need to simplify the screens.  Let’s cut down on the files
