### ISSUE TITLE
Setup Bottom Nav Bar, as well as drawer on left that will work globally

### ISSUE THREAD

**Issue by fredfalcon** [Bugheist/Flutter#8]

**Comment by Sparsh1212** [comment]
I would love to work on this. Can you please ellaborate more on what items do we want to add in the bottom navigation bar and in the drawer for as of now.

**Comment by fredfalcon** [comment]
This is mostly done nav and drawer are showing.  We next have to link the bottom nav to pages and make sure the drawer works on them.

**Comment by Sparsh1212** [comment]
Okay, I will do that. Can you please assign this work to me.
